[project]
name = "hirelens"
version = "0.1.0"
description = "hirelens using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.14"
dependencies = [
    "crewai[tools]==1.14.7"
]

[project.scripts]
hirelens = "hirelens.main:run"
run_crew = "hirelens.main:run"
train = "hirelens.main:train"
replay = "hirelens.main:replay"
test = "hirelens.main:test"
run_with_trigger = "hirelens.main:run_with_trigger"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
